### ISSUE TITLE
When deleting a note, the view should change to a note in the active notebook

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#15]
Right now it just changes to the first note

If there's more notes in the notebook, pick the first on found.
If not, pick the first note (in another notebook)

Or, maybe show "No notes in this notebook" text when there's no notebooks - and just show that and remove the window.location.hash, so it doesn't change notebook.

**Comment by calvinmorett** [comment]
Would it be beneficial to work co-cooperatively to outline a simple flow for how a user could move through a page, so maybe instead of a bug and defining, there might be a better solution or at least could open the way to more ideas that might be easier to create? 

For instance, this bug could be coded, instead of opening a note already in the notebook on delete, to just open a full view of the current notebook.

**Comment by xy2z** [comment]
I do think this is something look into, altough right now I think I'm going to hold on to trying to release a basic version that works, and then improve over time. So I'm going to do the easiest here and that is to just show another note in the active notebook.

I have alot of features that I will look into after the first couple of releases are out, and stable, but I'm not sure if I want to flood the issues with them? But I think I will edit the README to include what I wish v1.0 will have.

I hope when v1.0 stable is out, that some people could be interested in helping out and discussing things like your comment, and that's why I'm waiting.

**Comment by xy2z** [comment]
Fixed
