### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zvvysotskaya** [xy2z/dopenote#51]
Hi!
You have a stunning application! While application is getting larger it is hard to track errors. Would you mind if I create a feature test to your app?

**Comment by xy2z** [comment]
Hi and thanks!
A phpunit test? What did you want to test? There's quite a few scenarios, and still many more features to come.

**Comment by zvvysotskaya** [comment]
Yes, you are right, a phpunit test. I can try to do as many as you need.

**Comment by zvvysotskaya** [comment]
![image](https://user-images.githubusercontent.com/31147304/57172940-472c2000-6df5-11e9-9fa7-b68b254d113f.png)




I mean a phpunit test like this one. If you are agree, let me know and I‘ll continue.

**Comment by xy2z** [comment]
It would be nice if you could make tests for authorized users access to the NoteController and NotebookController, and see if response has `result: true`.
Methods like `create`, `delete`, etc.

Pure HTTP tests like "a_user_can_login_and_register" is not really needed imo, since it's just checking if the path exists.

**Comment by zvvysotskaya** [comment]
Thank you so much for your reply. I’ll remove ‘’a_user_can_login_and_register”  and proceed to make tests for NotebookController and NoteController.
